package com.example.moviedb.core.model


data class TvShowDetails(
    val id: Int,
    val name: String,
    val overview: String,
    val posterPath: String?,
    val backdropPath: String?,
    val adult: Boolean = false,
    val firstAirDate: String? = null,
    val lastAirDate: String? = null,
    val numberOfEpisodes: Int = 0,
    val numberOfSeasons: Int = 0,
    val episodeRunTime: List<Int> = emptyList(),
    val status: String? = null,
    val tagline: String? = null,
    val type: String? = null,
    val voteAverage: Double = 0.0,
    val voteCount: Int = 0,
    val popularity: Double = 0.0,
    val originalName: String = name,
    val originalLanguage: String = "",
    val originCountry: List<String> = emptyList(),
    val homepage: String? = null,
    val inProduction: Boolean = false,
    val languages: List<String> = emptyList(),
    val genres: List<String> = emptyList(),
    val networks: List<String> = emptyList(),
    val productionCompanies: List<String> = emptyList(),
    val productionCountries: List<String> = emptyList(),
    val spokenLanguages: List<String> = emptyList(),
    val seasonsCount: Int = 0,
    val createdBy: List<String> = emptyList(),
    val lastEpisodeName: String? = null,
    val lastEpisodeAirDate: String? = null,
    val nextEpisodeName: String? = null,
    val nextEpisodeAirDate: String? = null
)
