package com.example.moviedb.core.model


data class TvShowDetails(
    val id: Int = 0,
    val name: String = "",
    val overview: String = "",
    val posterPath: String = "",
    val backdropPath: String = "",
    val adult: Boolean = true,
    val firstAirDate: String = "",
    val lastAirDate: String = "",
    val numberOfEpisodes: Int = 0,
    val numberOfSeasons: Int = 0,
    val episodeRunTime: List<Int> = emptyList(),
    val status: String = "",
    val tagline: String = "",
    val type: String = "",
    val voteAverage: Double = 0.0,
    val voteCount: Int = 0,
    val popularity: Double = 0.0,
    val originalName: String = "",
    val originalLanguage: String = "",
    val originCountry: List<String> = emptyList(),
    val homepage: String = "",
    val inProduction: Boolean = true,
    val languages: List<String> = emptyList(),
    val genres: List<String> = emptyList(),
    val networks: List<String> = emptyList(),
    val productionCompanies: List<String> = emptyList(),
    val productionCountries: List<String> = emptyList(),
    val spokenLanguages: List<String> = emptyList(),
    val seasonsCount: Int = 0,
    val createdBy: List<String> = emptyList(),
    val lastEpisodeName: String = "",
    val lastEpisodeAirDate: String = "",
    val nextEpisodeToAir: String? = "",
    val nextEpisodeAirDate: String = ""
)
